buildscript {
  repositories {
    mavenCentral()
    gradlePluginPortal()
    mavenLocal()
    google()
    maven { url = 'https://central.sonatype.com/repository/maven-snapshots/' }
  }
  dependencies {


  }
}
plugins {
  id 'java'
  id 'com.github.johnrengelman.shadow' version '8.1.1'   // <-- CHANGE THIS LINE
}
allprojects {
  apply plugin: 'eclipse'
  apply plugin: 'idea'

  // This allows you to "Build and run using IntelliJ IDEA", an option in IDEA's Settings.
  idea {
    module {
      outputDir = file('build/classes/java/main')
      testOutputDir = file('build/classes/java/test')
    }
  }
}

configure(subprojects) {
  apply plugin: 'java-library'
  java.sourceCompatibility = 21

  // From https://lyze.dev/2021/04/29/libGDX-Internal-Assets-List/
  // The article can be helpful when using assets.txt in your project.
  tasks.register('generateAssetList') {
    inputs.dir("${project.rootDir}/assets/")
    // projectFolder/assets
    File assetsFolder = new File("${project.rootDir}/assets/")
    // projectFolder/assets/assets.txt
    File assetsFile = new File(assetsFolder, "assets.txt")
    // delete that file in case we've already created it
    assetsFile.delete()

    // iterate through all files inside that folder
    // convert it to a relative path
    // and append it to the file assets.txt
    fileTree(assetsFolder).collect { assetsFolder.relativePath(it) }.sort().each {
      assetsFile.append(it + "\n")
    }
  }
  processResources.dependsOn 'generateAssetList'

  compileJava {
    options.incremental = true
  }
}

subprojects {
  version = "$projectVersion"
  ext.appName = 'AP Graphic Project'
  repositories {
    mavenCentral()
    // You may want to remove the following line if you have errors downloading dependencies.
    mavenLocal()
    maven { url = 'https://central.sonatype.com/repository/maven-snapshots/' }
    maven { url = 'https://jitpack.io' }
  }
}

eclipse.project.name = 'AP Graphic Project' + '-parent'
configurations {
  gdxTools
}

repositories {
  mavenCentral()
}

dependencies {
  gdxTools "com.badlogic.gdx:gdx-tools:1.12.1"
  gdxTools "com.badlogic.gdx:gdx:1.12.1"
}

tasks.register('packKnight', JavaExec) {
  mainClass = 'com.badlogic.gdx.tools.texturepacker.TexturePacker'
  classpath  = configurations.gdxTools
  workingDir = rootDir
  args = ['assets/sprites/knight', 'assets/sprites', 'knight']
}
